### ISSUE TITLE
部分数据有误

### ISSUE THREAD

**Issue by agiapp** [small-dream/China_Province_City#4]
部分数据组装有误：
如：济源市，code和name的值写反了。（模糊搜索："name": "4  会有很多这种出错的数据，原因是原网站HTML标签结构有变化，希望作者及时做一下调整）
![image](https://user-images.githubusercontent.com/23326671/73510324-af5b7100-441c-11ea-8295-0f0a8826098f.png)

**Comment by agiapp** [comment]
数据格式有误，就别更新了。很误导别人使用！
![image](https://user-images.githubusercontent.com/23326671/77991559-d370fb00-7356-11ea-9b0f-e5892be3ff62.png)

**Comment by small-dream** [comment]
已修改，谢谢
