### ISSUE TITLE
处理特殊 市 代码  name 和 code 写反了

### ISSUE THREAD

**Issue by BigBigBIgMan** [small-dream/China_Province_City#5]
处理特殊 市 代码  name 和 code 写反了

        //处理石河子 特殊 市，City Code 不以00结尾
        for (Province province : provinceList) {
            for (int k = 0; k < stringCodeList.size(); k++) {
                if (stringCodeList.get(k).startsWith(province.getCode().substring(0, 2))) {
                    City city = new City();
                    List<Area> areas = new ArrayList<Area>();
                    city.setName(stringCodeList.get(k));
                    city.setCode(stringNameList.get(k));
                    city.setAreaList(areas);
                    province.getCityList().add(city);
                }
            }
        }

https://user-images.githubusercontent.com/29669179/79038221-3d688a80-7c0a-11ea-8a35-b3247e018d78.png

**Comment by small-dream** [comment]
已修改，谢谢
